language: python

python:
        - "2.7"

virtualenv:
      system_site_packages: true

install:
        - sudo apt-get install python-qt4
        - sudo apt-get install qgis
        - sudo apt-get install python-qgis
        - sudo apt-get install vnc4server # to mock an X Server
        - pip install mock
        - pip install nose
        - pip install coverage
        - pip install coveralls
        - pip install psycopg2

before_script:
        - psql -U postgres -c "create extension postgis"
        - psql -c 'create database mydb;' -U postgres
        - psql -U postgres -c "ALTER USER postgres WITH PASSWORD 'postgres'"; 
        - echo -e "p4ssw0rd\np4ssw0rd\n" | vncserver -geometry 1024x768 :99
        - export DISPLAY=:99.0

script:  sh run_tests.sh # this runs tests with coverage

after_success:
    coveralls
